using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace sixbasiclib
{
    public static class PETSCII
    {

        public const byte CHAR_COLON = 0x3a;
        public const byte CHAR_QUOTE = 0x22;


        public static char FixCase(char c)
        {
            //Fix case
            if (c >= 'a' && c <= 'z')
            {
                return c.ToString().ToUpper()[0];
            }
            else
            {
                if (c >= 'A' && c <= 'Z')
                {
                    return c.ToString().ToLower()[0];
                }
                else
                {
                    return c;
                }

            }

        }
        public class Macro
        {
            public string Text { get; set; } = string.Empty;
            public string Replacement { get; set; } = string.Empty;
        }

        public static List<Macro> Macros = new List<Macro> {
                                           new Macro(){Text="{white}",Replacement="\x05"},
                                           new Macro(){Text="{disable_shift}",Replacement="\x08"},
                                           new Macro(){Text="{enable_shift}",Replacement="\x09"},
                                           new Macro(){Text="{lowercase}",Replacement="\x0e"},
                                           new Macro(){Text="{down}",Replacement="\x11"},
                                           new Macro(){Text="{reverse on}",Replacement="\x12"},
                                           new Macro(){Text="{home}",Replacement="\x13"},
                                           new Macro(){Text="{del}",Replacement="\x14"},
                                           new Macro(){Text="{red}",Replacement="\x1c"},
                                           new Macro(){Text="{right}",Replacement="\x1d"},
                                           new Macro(){Text="{green}",Replacement="\x1e"},
                                           new Macro(){Text="{blue}",Replacement="\x1f"},
                                           new Macro(){Text="{orange}",Replacement="\x81"},
                                           new Macro(){Text="{f1}",Replacement="\x85"},
                                           new Macro(){Text="{f3}",Replacement="\x86"},
                                           new Macro(){Text="{f5}",Replacement="\x87"},
                                           new Macro(){Text="{f7}",Replacement="\x88"},
                                           new Macro(){Text="{f2}",Replacement="\x89"},
                                           new Macro(){Text="{f4}",Replacement="\x8a"},
                                           new Macro(){Text="{f6}",Replacement="\x8b"},
                                           new Macro(){Text="{f8}",Replacement="\x8c"},
                                           new Macro(){Text="{uppercase}",Replacement="\x8e"},
                                           new Macro(){Text="{black}",Replacement="\x90"},
                                           new Macro(){Text="{up}",Replacement="\x91"},
                                           new Macro(){Text="{reverse off}",Replacement="\x92"},
                                           new Macro(){Text="{clear}",Replacement="\x93"},
                                           new Macro(){Text="{insert}",Replacement="\x94"},
                                           new Macro(){Text="{brown}",Replacement="\x95"},
                                           new Macro(){Text="{pink}",Replacement="\x96"},
                                           new Macro(){Text="{gray 1}",Replacement="\x97"},
                                           new Macro(){Text="{gray 2}",Replacement="\x98"},
                                           new Macro(){Text="{light green}",Replacement="\x99"},
                                           new Macro(){Text="{light blue}",Replacement="\x9a"},
                                           new Macro(){Text="{gray 3}",Replacement="\x9b"},
                                           new Macro(){Text="{purple}",Replacement="\x9c"},
                                           new Macro(){Text="{left}",Replacement="\x9d"},
                                           new Macro(){Text="{yellow}",Replacement="\x9e"},
                                           new Macro(){Text="{cyan}",Replacement="\x9f"},
			new Macro(){Text="{$00}",Replacement="\x00"},
            new Macro(){Text="{$01}",Replacement="\x01"},
            new Macro(){Text="{$02}",Replacement="\x02"},
            new Macro(){Text="{$03}",Replacement="\x03"},
            new Macro(){Text="{$04}",Replacement="\x04"},
            new Macro(){Text="{$05}",Replacement="\x05"},
            new Macro(){Text="{$06}",Replacement="\x06"},
            new Macro(){Text="{$07}",Replacement="\x07"},
            new Macro(){Text="{$08}",Replacement="\x08"},
            new Macro(){Text="{$09}",Replacement="\x09"},
            new Macro(){Text="{$0a}",Replacement="\x0a"},
            new Macro(){Text="{$0b}",Replacement="\x0b"},
            new Macro(){Text="{$0c}",Replacement="\x0c"},
            new Macro(){Text="{$0d}",Replacement="\x0d"},
            new Macro(){Text="{$0e}",Replacement="\x0e"},
            new Macro(){Text="{$0f}",Replacement="\x0f"},
            new Macro(){Text="{$10}",Replacement="\x10"},
            new Macro(){Text="{$11}",Replacement="\x11"},
            new Macro(){Text="{$12}",Replacement="\x12"},
            new Macro(){Text="{$13}",Replacement="\x13"},
            new Macro(){Text="{$14}",Replacement="\x14"},
            new Macro(){Text="{$15}",Replacement="\x15"},
            new Macro(){Text="{$16}",Replacement="\x16"},
            new Macro(){Text="{$17}",Replacement="\x17"},
            new Macro(){Text="{$18}",Replacement="\x18"},
            new Macro(){Text="{$19}",Replacement="\x19"},
            new Macro(){Text="{$1a}",Replacement="\x1a"},
            new Macro(){Text="{$1b}",Replacement="\x1b"},
            new Macro(){Text="{$1c}",Replacement="\x1c"},
            new Macro(){Text="{$1d}",Replacement="\x1d"},
            new Macro(){Text="{$1e}",Replacement="\x1e"},
            new Macro(){Text="{$1f}",Replacement="\x1f"},
            new Macro(){Text="{$20}",Replacement="\x20"},
            new Macro(){Text="{$21}",Replacement="\x21"},
            new Macro(){Text="{$22}",Replacement="\x22"},
            new Macro(){Text="{$23}",Replacement="\x23"},
            new Macro(){Text="{$24}",Replacement="\x24"},
            new Macro(){Text="{$25}",Replacement="\x25"},
            new Macro(){Text="{$26}",Replacement="\x26"},
            new Macro(){Text="{$27}",Replacement="\x27"},
            new Macro(){Text="{$28}",Replacement="\x28"},
            new Macro(){Text="{$29}",Replacement="\x29"},
            new Macro(){Text="{$2a}",Replacement="\x2a"},
            new Macro(){Text="{$2b}",Replacement="\x2b"},
            new Macro(){Text="{$2c}",Replacement="\x2c"},
            new Macro(){Text="{$2d}",Replacement="\x2d"},
            new Macro(){Text="{$2e}",Replacement="\x2e"},
            new Macro(){Text="{$2f}",Replacement="\x2f"},
            new Macro(){Text="{$30}",Replacement="\x30"},
            new Macro(){Text="{$31}",Replacement="\x31"},
            new Macro(){Text="{$32}",Replacement="\x32"},
            new Macro(){Text="{$33}",Replacement="\x33"},
            new Macro(){Text="{$34}",Replacement="\x34"},
            new Macro(){Text="{$35}",Replacement="\x35"},
            new Macro(){Text="{$36}",Replacement="\x36"},
            new Macro(){Text="{$37}",Replacement="\x37"},
            new Macro(){Text="{$38}",Replacement="\x38"},
            new Macro(){Text="{$39}",Replacement="\x39"},
            new Macro(){Text="{$3a}",Replacement="\x3a"},
            new Macro(){Text="{$3b}",Replacement="\x3b"},
            new Macro(){Text="{$3c}",Replacement="\x3c"},
            new Macro(){Text="{$3d}",Replacement="\x3d"},
            new Macro(){Text="{$3e}",Replacement="\x3e"},
            new Macro(){Text="{$3f}",Replacement="\x3f"},
			new Macro(){Text="{$40}",Replacement="\x40"},
            new Macro(){Text="{$41}",Replacement="\x41"},
            new Macro(){Text="{$42}",Replacement="\x42"},
            new Macro(){Text="{$43}",Replacement="\x43"},
            new Macro(){Text="{$44}",Replacement="\x44"},
            new Macro(){Text="{$45}",Replacement="\x45"},
            new Macro(){Text="{$46}",Replacement="\x46"},
            new Macro(){Text="{$47}",Replacement="\x47"},
            new Macro(){Text="{$48}",Replacement="\x48"},
            new Macro(){Text="{$49}",Replacement="\x49"},
            new Macro(){Text="{$4a}",Replacement="\x4a"},
            new Macro(){Text="{$4b}",Replacement="\x4b"},
            new Macro(){Text="{$4c}",Replacement="\x4c"},
            new Macro(){Text="{$4d}",Replacement="\x4d"},
            new Macro(){Text="{$4e}",Replacement="\x4e"},
            new Macro(){Text="{$4f}",Replacement="\x4f"},
            new Macro(){Text="{$50}",Replacement="\x50"},
            new Macro(){Text="{$51}",Replacement="\x51"},
            new Macro(){Text="{$52}",Replacement="\x52"},
            new Macro(){Text="{$53}",Replacement="\x53"},
            new Macro(){Text="{$54}",Replacement="\x54"},
            new Macro(){Text="{$55}",Replacement="\x55"},
            new Macro(){Text="{$56}",Replacement="\x56"},
            new Macro(){Text="{$57}",Replacement="\x57"},
            new Macro(){Text="{$58}",Replacement="\x58"},
            new Macro(){Text="{$59}",Replacement="\x59"},
            new Macro(){Text="{$5a}",Replacement="\x5a"},
            new Macro(){Text="{$5b}",Replacement="\x5b"},
            new Macro(){Text="{$5c}",Replacement="\x5c"},
            new Macro(){Text="{$5d}",Replacement="\x5d"},
            new Macro(){Text="{$5e}",Replacement="\x5e"},
            new Macro(){Text="{$5f}",Replacement="\x5f"},
            new Macro(){Text="{$60}",Replacement="\x60"},
            new Macro(){Text="{$61}",Replacement="\x61"},
            new Macro(){Text="{$62}",Replacement="\x62"},
            new Macro(){Text="{$63}",Replacement="\x63"},
            new Macro(){Text="{$64}",Replacement="\x64"},
            new Macro(){Text="{$65}",Replacement="\x65"},
            new Macro(){Text="{$66}",Replacement="\x66"},
            new Macro(){Text="{$67}",Replacement="\x67"},
            new Macro(){Text="{$68}",Replacement="\x68"},
            new Macro(){Text="{$69}",Replacement="\x69"},
            new Macro(){Text="{$6a}",Replacement="\x6a"},
            new Macro(){Text="{$6b}",Replacement="\x6b"},
            new Macro(){Text="{$6c}",Replacement="\x6c"},
            new Macro(){Text="{$6d}",Replacement="\x6d"},
            new Macro(){Text="{$6e}",Replacement="\x6e"},
            new Macro(){Text="{$6f}",Replacement="\x6f"},
            new Macro(){Text="{$70}",Replacement="\x70"},
            new Macro(){Text="{$71}",Replacement="\x71"},
            new Macro(){Text="{$72}",Replacement="\x72"},
            new Macro(){Text="{$73}",Replacement="\x73"},
            new Macro(){Text="{$74}",Replacement="\x74"},
            new Macro(){Text="{$75}",Replacement="\x75"},
            new Macro(){Text="{$76}",Replacement="\x76"},
            new Macro(){Text="{$77}",Replacement="\x77"},
            new Macro(){Text="{$78}",Replacement="\x78"},
            new Macro(){Text="{$79}",Replacement="\x79"},
            new Macro(){Text="{$7a}",Replacement="\x7a"},
            new Macro(){Text="{$7b}",Replacement="\x7b"},
            new Macro(){Text="{$7c}",Replacement="\x7c"},
            new Macro(){Text="{$7d}",Replacement="\x7d"},
            new Macro(){Text="{$7e}",Replacement="\x7e"},
            new Macro(){Text="{$7f}",Replacement="\x7f"},
			new Macro(){Text="{$80}",Replacement="\x80"},
            new Macro(){Text="{$81}",Replacement="\x81"},
            new Macro(){Text="{$82}",Replacement="\x82"},
            new Macro(){Text="{$83}",Replacement="\x83"},
            new Macro(){Text="{$84}",Replacement="\x84"},
            new Macro(){Text="{$85}",Replacement="\x85"},
            new Macro(){Text="{$86}",Replacement="\x86"},
            new Macro(){Text="{$87}",Replacement="\x87"},
            new Macro(){Text="{$88}",Replacement="\x88"},
            new Macro(){Text="{$89}",Replacement="\x89"},
            new Macro(){Text="{$8a}",Replacement="\x8a"},
            new Macro(){Text="{$8b}",Replacement="\x8b"},
            new Macro(){Text="{$8c}",Replacement="\x8c"},
            new Macro(){Text="{$8d}",Replacement="\x8d"},
            new Macro(){Text="{$8e}",Replacement="\x8e"},
            new Macro(){Text="{$8f}",Replacement="\x8f"},
            new Macro(){Text="{$90}",Replacement="\x90"},
            new Macro(){Text="{$91}",Replacement="\x91"},
            new Macro(){Text="{$92}",Replacement="\x92"},
            new Macro(){Text="{$93}",Replacement="\x93"},
            new Macro(){Text="{$94}",Replacement="\x94"},
            new Macro(){Text="{$95}",Replacement="\x95"},
            new Macro(){Text="{$96}",Replacement="\x96"},
            new Macro(){Text="{$97}",Replacement="\x97"},
            new Macro(){Text="{$98}",Replacement="\x98"},
            new Macro(){Text="{$99}",Replacement="\x99"},
            new Macro(){Text="{$9a}",Replacement="\x9a"},
            new Macro(){Text="{$9b}",Replacement="\x9b"},
            new Macro(){Text="{$9c}",Replacement="\x9c"},
            new Macro(){Text="{$9d}",Replacement="\x9d"},
            new Macro(){Text="{$9e}",Replacement="\x9e"},
            new Macro(){Text="{$9f}",Replacement="\x9f"},
            new Macro(){Text="{$a0}",Replacement="\xa0"},
            new Macro(){Text="{$a1}",Replacement="\xa1"},
            new Macro(){Text="{$a2}",Replacement="\xa2"},
            new Macro(){Text="{$a3}",Replacement="\xa3"},
            new Macro(){Text="{$a4}",Replacement="\xa4"},
            new Macro(){Text="{$a5}",Replacement="\xa5"},
            new Macro(){Text="{$a6}",Replacement="\xa6"},
            new Macro(){Text="{$a7}",Replacement="\xa7"},
            new Macro(){Text="{$a8}",Replacement="\xa8"},
            new Macro(){Text="{$a9}",Replacement="\xa9"},
            new Macro(){Text="{$aa}",Replacement="\xaa"},
            new Macro(){Text="{$ab}",Replacement="\xab"},
            new Macro(){Text="{$ac}",Replacement="\xac"},
            new Macro(){Text="{$ad}",Replacement="\xad"},
            new Macro(){Text="{$ae}",Replacement="\xae"},
            new Macro(){Text="{$af}",Replacement="\xaf"},
            new Macro(){Text="{$b0}",Replacement="\xb0"},
            new Macro(){Text="{$b1}",Replacement="\xb1"},
            new Macro(){Text="{$b2}",Replacement="\xb2"},
            new Macro(){Text="{$b3}",Replacement="\xb3"},
            new Macro(){Text="{$b4}",Replacement="\xb4"},
            new Macro(){Text="{$b5}",Replacement="\xb5"},
            new Macro(){Text="{$b6}",Replacement="\xb6"},
            new Macro(){Text="{$b7}",Replacement="\xb7"},
            new Macro(){Text="{$b8}",Replacement="\xb8"},
            new Macro(){Text="{$b9}",Replacement="\xb9"},
            new Macro(){Text="{$ba}",Replacement="\xba"},
            new Macro(){Text="{$bb}",Replacement="\xbb"},
            new Macro(){Text="{$bc}",Replacement="\xbc"},
            new Macro(){Text="{$bd}",Replacement="\xbd"},
            new Macro(){Text="{$be}",Replacement="\xbe"},
            new Macro(){Text="{$bf}",Replacement="\xbf"},
			new Macro(){Text="{$c0}",Replacement="\xc0"},
            new Macro(){Text="{$c1}",Replacement="\xc1"},
            new Macro(){Text="{$c2}",Replacement="\xc2"},
            new Macro(){Text="{$c3}",Replacement="\xc3"},
            new Macro(){Text="{$c4}",Replacement="\xc4"},
            new Macro(){Text="{$c5}",Replacement="\xc5"},
            new Macro(){Text="{$c6}",Replacement="\xc6"},
            new Macro(){Text="{$c7}",Replacement="\xc7"},
            new Macro(){Text="{$c8}",Replacement="\xc8"},
            new Macro(){Text="{$c9}",Replacement="\xc9"},
            new Macro(){Text="{$ca}",Replacement="\xca"},
            new Macro(){Text="{$cb}",Replacement="\xcb"},
            new Macro(){Text="{$cc}",Replacement="\xcc"},
            new Macro(){Text="{$cd}",Replacement="\xcd"},
            new Macro(){Text="{$ce}",Replacement="\xce"},
            new Macro(){Text="{$cf}",Replacement="\xcf"},
            new Macro(){Text="{$d0}",Replacement="\xd0"},
            new Macro(){Text="{$d1}",Replacement="\xd1"},
            new Macro(){Text="{$d2}",Replacement="\xd2"},
            new Macro(){Text="{$d3}",Replacement="\xd3"},
            new Macro(){Text="{$d4}",Replacement="\xd4"},
            new Macro(){Text="{$d5}",Replacement="\xd5"},
            new Macro(){Text="{$d6}",Replacement="\xd6"},
            new Macro(){Text="{$d7}",Replacement="\xd7"},
            new Macro(){Text="{$d8}",Replacement="\xd8"},
            new Macro(){Text="{$d9}",Replacement="\xd9"},
            new Macro(){Text="{$da}",Replacement="\xda"},
            new Macro(){Text="{$db}",Replacement="\xdb"},
            new Macro(){Text="{$dc}",Replacement="\xdc"},
            new Macro(){Text="{$dd}",Replacement="\xdd"},
            new Macro(){Text="{$de}",Replacement="\xde"},
            new Macro(){Text="{$df}",Replacement="\xdf"},
            new Macro(){Text="{$e0}",Replacement="\xe0"},
            new Macro(){Text="{$e1}",Replacement="\xe1"},
            new Macro(){Text="{$e2}",Replacement="\xe2"},
            new Macro(){Text="{$e3}",Replacement="\xe3"},
            new Macro(){Text="{$e4}",Replacement="\xe4"},
            new Macro(){Text="{$e5}",Replacement="\xe5"},
            new Macro(){Text="{$e6}",Replacement="\xe6"},
            new Macro(){Text="{$e7}",Replacement="\xe7"},
            new Macro(){Text="{$e8}",Replacement="\xe8"},
            new Macro(){Text="{$e9}",Replacement="\xe9"},
            new Macro(){Text="{$ea}",Replacement="\xea"},
            new Macro(){Text="{$eb}",Replacement="\xeb"},
            new Macro(){Text="{$ec}",Replacement="\xec"},
            new Macro(){Text="{$ed}",Replacement="\xed"},
            new Macro(){Text="{$ee}",Replacement="\xee"},
            new Macro(){Text="{$ef}",Replacement="\xef"},
            new Macro(){Text="{$f0}",Replacement="\xf0"},
            new Macro(){Text="{$f1}",Replacement="\xf1"},
            new Macro(){Text="{$f2}",Replacement="\xf2"},
            new Macro(){Text="{$f3}",Replacement="\xf3"},
            new Macro(){Text="{$f4}",Replacement="\xf4"},
            new Macro(){Text="{$f5}",Replacement="\xf5"},
            new Macro(){Text="{$f6}",Replacement="\xf6"},
            new Macro(){Text="{$f7}",Replacement="\xf7"},
            new Macro(){Text="{$f8}",Replacement="\xf8"},
            new Macro(){Text="{$f9}",Replacement="\xf9"},
            new Macro(){Text="{$fa}",Replacement="\xfa"},
            new Macro(){Text="{$fb}",Replacement="\xfb"},
            new Macro(){Text="{$fc}",Replacement="\xfc"},
            new Macro(){Text="{$fd}",Replacement="\xfd"},
            new Macro(){Text="{$fe}",Replacement="\xfe"},
            new Macro(){Text="{$ff}",Replacement="\xff"}
                                       };

        public static string[] Table = {"{$00}","{$01}","{$02}","{$03}","{$04}","{white}","{$06}","{$07}",
                                    "{disable_shift}","{enable_shift}","{$0a}","{$0b}","{$0c}","{$0d}","{lowercase}","{$0f}",
                                    "{$10}","{down}","{reverse on}","{home}","{del}","{$15}","{$16}","{$17}",
                                    "{$18}","{$19}","{$1a}","{$1b}","{red}","{right}","{green}","{blue}",
                                    " ","!","\"","#","$","%","&","'",
                                    "(",")","*","+",",","-",".","/",
                                    "0","1","2","3","4","5","6","7", //0x30-0x37
                                    "8","9",":",";","<","=",">","?", //0x38-0x3f
                                    "@","a","b","c","d","e","f","g", //0x40-0x47
                                    "h","i","j","k","l","m","n","o", //0x48-0x4f
                                    "p","q","r","s","t","u","v","w", //0x50-0x57
                                    "x","y","z","[","\\","]","^","_", //0x58-0x5f
                                    "`","A","B","C","D","E","F","G", //0x60-0x67
                                    "H","I","J","K","L","M","N","O", //0x68-0x6f
                                    "P","Q","R","S","T","U","V","W", //x070-0x77
                                    "X","Y","Z","{","|","}","~","{$7f}", //0x78-0x7f
                          "{$80}","{orange}","{$82}","{$83}","{$84}","{f1}","{f3}","{f5}",
                          "{f7}","{f2}","{f4}","{f6}","{f8}","{$8d}","{uppercase}","{$8f}",       //0x80-0x8F
                          "{black}","{up}","{reverse off}","{clear}","{insert}","{brown}","{pink}","{gray 1}",
                          "{gray 2}","{light green}","{light blue}","{gray 3}","{purple}","{left}","{yellow}","{cyan}",       //0x90-0x9F
                          "{$a0}","{$a1}","{$a2}","{$a3}","{$a4}","{$a5}","{$a6}","{$a7}",
                          "{$a8}","{$a9}","{$aa}","{$ab}","{$ac}","{$ad}","{$ae}","{$af}",       //0xA0-0xAF
                          "{$b0}","{$b1}","{$b2}","{$b3}","{$b4}","{$b5}","{$b6}","{$b7}",
                          "{$b8}","{$b9}","{$ba}","{$bb}","{$bc}","{$bd}","{$be}","{$bf}",       //0xB0-0xBF
                                    "`","A","B","C","D","E","F","G", //0xc0-0xc7
                                    "H","I","J","K","L","M","N","O", //0xc8-0xcf
                                    "P","Q","R","S","T","U","V","W", //x0d0-0xd7
                                    "X","Y","Z","{","|","}","~","{$7f}", //0xd8-0xdf
                          "{$e0}","{$e1}","{$e2}","{$e3}","{$e4}","{$e5}","{$e6}","{$e7}",
                          "{$e8}","{$e9}","{$ea}","{$eb}","{$ec}","{$ed}","{$ee}","{$ef}",       //0xE0-0xEF
                          "{$f0}","{$f1}","{$f2}","{$f3}","{$f4}","{$f5}","{$f6}","{$f7}",
                          "{$f8}","{$f9}","{$fa}","{$fb}","{$fc}","{$fd}","{$fe}","{$ff}" };//0xF0-0xFF

    }
}
